# Copyright (c) Facebook, Inc. and its affiliates.

# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

version: '3'

volumes:
  whatsappMedia1:
    driver: local
  mysqlData1:
    driver: local

services:
  db1:
    image: mysql:5.7.26
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testpass1
      MYSQL_USER: testuser1
      MYSQL_PASSWORD: testpass1
      MYSQL_TCP_PORT: 3306
    expose:
        - "3306"
    volumes:
     - mysqlData1:/var/lib/mysql
    network_mode: bridge
  wacore1:
    image: docker.whatsapp.biz/coreapp:v${WA_API_VERSION:-2.35.4?Run docker-compose with env var WA_API_VERSION (ex. WA_API_VERSION=2.33.3 docker-compose <command> <options>)}
    command: ["/opt/whatsapp/bin/wait_on_mysql.sh", "/opt/whatsapp/bin/launch_within_docker.sh"]
    volumes:
     - whatsappMedia1:/usr/local/wamedia
    env_file:
      - db.env
    environment:
      # This is the version of the docker templates being used to run WhatsApp Business API
      WA_RUNNING_ENV_VERSION: v2.2.3
      ORCHESTRATION: DOCKER-COMPOSE
    depends_on:
      - "db1"
    network_mode: bridge
    links:
      - db1
  waweb1:
    image: docker.whatsapp.biz/web:v${WA_API_VERSION:-2.35.4?Run docker-compose with env var WA_API_VERSION (ex. WA_API_VERSION=2.33.3 docker-compose <command> <options>)}
    command: ["/opt/whatsapp/bin/wait_on_mysql.sh", "/opt/whatsapp/bin/launch_within_docker.sh"]
    ports:
     - "9092:443"
    volumes:
     - whatsappMedia1:/usr/local/wamedia
    env_file:
      - db.env
    environment:
      WACORE_HOSTNAME: wacore1
      # This is the version of the docker templates being used to run WhatsApp Business API
      WA_RUNNING_ENV_VERSION: v2.2.3
      ORCHESTRATION: DOCKER-COMPOSE
    depends_on:
      - "db1"
      - "wacore1"
    links:
      - db1
      - wacore1
    network_mode: bridge
